order 기능 구현
HICC-2024-1-Project/HiccOrder-Backend pull request #7
Opened 2024-07-03 01:36 UTC by GJYeon

Order 기능 구현

## 주요 변경 내용
-api
  - order/
      - `GET: 전체 주문 목록 가져오기
      - {tableid}/
          - `GET: 테이블에서 주문한 메뉴 목록 확인 
          - `POST: 테이블에 메뉴 주문 
          - {orderid}/
              - `PATCH: 주문한 메뉴 수정 
              - `DELETE: 주문한 메뉴 삭제 

## 참고 사항
-payment/ POST: 테이블 결제 개발 예정

## 남은 작업 내용
-

## 참고용 시연 사진
-order/ GET: 전체 주문 목록 가져오기
<img width="655" alt="전체주문목록확인" src="https://github.com/HICC-2024-1-Project/HiccOrder-Backend/assets/132131162/921f6cda-0b45-4cf8-bdef-c0f52c551c7e">

-order/{tableid}/GET: 테이블에서 주문한 메뉴 목록 확인 
<img width="639" alt="테이블메뉴주문현황" src="https://github.com/HICC-2024-1-Project/HiccOrder-Backend/assets/132131162/0f324012-5a28-4227-98df-cc1d61023ea8">

-order/{tableid}/POST: 테이블에 메뉴 주문 
<img width="664" alt="테이블에메뉴주문" src="https://github.com/HICC-2024-1-Project/HiccOrder-Backend/assets/132131162/2754bb80-bc3d-48e4-92c7-87440d0307c2">

-order/{tableid}/{orderid}/PATCH: 주문한 메뉴 수정 
메뉴 수정
<img width="644" alt="테이블주문수정1" src="https://github.com/HICC-2024-1-Project/HiccOrder-Backend/assets/132131162/3db135aa-785d-4aef-b7b7-697e2f71a41b">

수정 후
<img width="653" alt="주문수정후" src="https://github.com/HICC-2024-1-Project/HiccOrder-Backend/assets/132131162/7629549a-1f72-4e3e-b9c4-ef5b9d2a94eb">

-order/{tableid}/{orderid}/DELETE: 주문한 메뉴 삭제
삭제 전
<img width="655" alt="주문삭제전" src="https://github.com/HICC-2024-1-Project/HiccOrder-Backend/assets/132131162/5c50aafc-9565-45af-840b-b583e4935461">

삭제
<img width="658" alt="주문삭제" src="https://github.com/HICC-2024-1-Project/HiccOrder-Backend/assets/132131162/335fa254-dd46-49fb-898a-89c4bca2660a">

삭제 후
<img width="655" alt="주문삭제후" src="https://github.com/HICC-2024-1-Project/HiccOrder-Backend/assets/132131162/dcecd169-3b9a-4e4f-beb1-237237e6effc">

2024-07-03 04:37 UTC, darkenergy814 requested changes
코멘트 단 부분 수정 바랍니다..! 나머지는 괜찮은 것 같습니다!!

2024-07-03 04:37 UTC, darkenergy814 commented on backend/accounts/models.py
> +    order_id = models.CharField(max_length=100, null=True, blank=True, unique=True)
order id는 order 테이블에 데이터가 생기면 자동으로 생성됩니다. 굳이 따로 선언하지 않아도 됩니다.

2024-07-03 04:37 UTC, darkenergy814 commented on backend/accounts/views/booth.py
> +        if user == instance:  # 토큰의 유저 정보와 유저 정보가 일치할 때만 허가
권한 확인하는 코드가 이미 common.py 정의되어있습니다. 해당 코드를 활용하면 좋을 것 같습니다.

2024-07-03 04:37 UTC, darkenergy814 commented on backend/accounts/views/booth.py
> +            return Response({"message": "주문을 생성할 수 없습니다. 잘못된 요청입니다."}, status=status.HTTP_400_BAD_REQUEST)
조리 되지 않은 메뉴가 있는 경우에 대한 예외처리가 안 되어있습니다. 확인 바랍니다.

2024-07-04 14:03 UTC, GJYeon commented on backend/accounts/views/booth.py
> +        if user == instance:  # 토큰의 유저 정보와 유저 정보가 일치할 때만 허가
수정 완료하였습니다!!

2024-07-05 00:35 UTC, darkenergy814 approved these changes

2024-07-05 00:35 UTC, darkenergy814 commented on backend/accounts/views/booth.py
> +                Response({"message": "잘못된 요청입니다."}, status=status.HTTP_400_BAD_REQUEST)
요거

2024-07-05 00:35 UTC, darkenergy814 commented on backend/accounts/views/booth.py
> +                Response({"message": "잘못된 요청입니다."}, status=status.HTTP_400_BAD_REQUEST)
요거

2024-07-05 00:35 UTC, merged